services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_API_URL=${VITE_API_URL}
        image: ${NGINX_IMAGE_NAME:-icpac/sewaa-proxy-server}
        container_name: ${NGINX_CNTR_NAME:-cgan-proxy}
        restart: ${RESTART_POLICY:-always}
        ports:
            - ${HTTP_HOST_IP:-0.0.0.0}:${HTTP_HOST_PORT:-80}:80
            - ${HTTPS_HOST_IP:-0.0.0.0}:${HTTPS_HOST_PORT:-443}:443
        environment:
            - VITE_API_URL
            - OPENAPI_URL
        volumes:
            - ${SITE_CONF:-./nginx/live-site.conf}:/etc/nginx/conf.d/site.conf
            - ${FORECASTS_DATA_DIR:-./data/forecasts}:${PUBLIC_DATA_DIR:-/opt/data}
            - ${API_CACHE_DIR:-../fast-cgan/cache}:/opt/api-cache
            - ${NGINX_SSL_CERTS:-./data/ssl-certs}:${CERTS_DIR:-/var/srv/ssl-certs}
